# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir .

# Ensure unbuffered output for stdio
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["python", "-m", "mcp_server_servicenow.cli"]
